server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ticketoffice
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
  jackson:
    serialization:
      write_dates_as_timestamps: false

jwt:
  secret: tick3tsecr1t
  validity-minutes: 20